### ISSUE TITLE
Problem beim Anlegen eines Unterformular-Eintrages

### ISSUE THREAD

**Issue by dijoje** [saierd/python-nuclos#4]
Hallo Herr Saier,
ich habe gerade versucht eine Auftragsposition zu einem Auftrag hinzuzufügen mit 
`
neuerAuftrag.create_dependency_by_name('Auftragsposition')`

Dies ging ebenso wenig wie der Aufruf per create_Auftragsposition()
Vielleicht haben Sie eine Idee dazu. Wenn ich die Auftragsposition eigenständig erzeuge und dann den Auftrag dieser zuweise funktioniert es.

Zur Info: Auftrag ist ein BO mit Statusmodell, Auftragsposition nicht. Ich verwende die Nuclos-Version 4.34.0 . Unten stehend ist einmal die Fehlermeldung des Scriptes und noch weiter unten die Fehlermeldung im DEBUG Mode.

Ansonsten finde ich immer noch, dass Sie eine schöne "pythonische" Schnittstelle entwickelt haben mitder es sich gut arbeiten läßt.

Viele Grüße 
Dirk Jende-Holzmann

**Fehlermeldung vom Script**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nuclos/nuclos/nuclos.py", line 981, in create_dependency_by_name
    dependency_id = self._get_dependency_id_by_name(name)
  File "/home/nuclos/nuclos/nuclos.py", line 946, in _get_dependency_id_by_name
    for dep in self._dependency_metas:
  File "/home/nuclos/nuclos/nuclos.py", line 105, in __call__
    self.cache[args] = self.f(*args)
  File "/home/nuclos/nuclos/nuclos.py", line 930, in _dependency_metas
    deps = self.data["subBos"]
  File "/home/nuclos/nuclos/nuclos.py", line 727, in data
    raise NuclosException("Attempting to access data of an uninitialized business object instance.")
nuclos.NuclosException: Attempting to access data of an uninitialized business object instance.

**Meldung im Debug-Modus**

ERROR	26.08.2019 13:07:22	HTTP Error 404: 
Traceback (most recent call last):
  File "/home/nuclos/nuclos/nuclos.py", line 357, in request
    result = urllib.request.urlopen(request)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./auftragimport.py", line 49, in <module>
    NeueAP=neuerAuftrag.create_dependency_by_name("Positionen")
  File "/home/nuclos/nuclos/nuclos.py", line 981, in create_dependency_by_name
    dependency_id = self._get_dependency_id_by_name(name)
  File "/home/nuclos/nuclos/nuclos.py", line 946, in _get_dependency_id_by_name
    for dep in self._dependency_metas:
  File "/home/nuclos/nuclos/nuclos.py", line 105, in __call__
    self.cache[args] = self.f(*args)
  File "/home/nuclos/nuclos/nuclos.py", line 934, in _dependency_metas
    metas[dep] = self._nuclos.request(deps[dep]["links"]["boMeta"]["href"])
  File "/home/nuclos/nuclos/nuclos.py", line 384, in request
    raise NuclosHTTPException(e)
nuclos.NuclosHTTPException: HTTP Exception: 404 -

**Comment by saierd** [comment]
Der Fehler 404 aus der API kommt wohl entweder daher, dass sich die API verändert hat und Python nun eine falsche URL benutzt oder dass es einen Fehler auf dem Server gab (die Nuclos API nimmt es mit den Status Codes manchmal nicht so genau). Mit 4.34 habe ich noch nie getestet, aber ich konnte auf Anhieb keine Informationen über kürzlichen Änderungen an der REST API finden. Daher ist es vermutlich ein Fehler auf dem Server.

Mit dem Workaround scheint es ja erstmal zu funktionieren. Falls Sie aber zufällig noch einmal über den Fehler stolpern, könnten Sie dann einmal ins Server Log schauen und eventuelle Exceptions hier posten?

**Comment by saierd** [comment]
Entschuldigen Sie bitte die ziemlich lange Wartezeit, ich hatte dieses Ticket ganz vergessen. Nun habe ich selbst Nuclos aktualisiert (war bisher noch mit Version 4.30 unterwegs) und bin dabei vermutlich über den selben Fehler gestolpert. Nuclos hat in Version 4.32 die HATEOAS Links verändert, die von der API zurückgegeben werden. Falls das auch Ihr Fehler war sollte das mit 3390d453952744c9bc1ec2d4c1ddc99adf2335e3 / Version 1.8 behoben sein.

**Comment by dijoje** [comment]
Hallo Herr Saier,
macht nichts, ich habe die Nachricht erst jetzt gelesen, da ich mein GMail
Konto nur noch selten lese. Danke für die Anpassungen und schön, dass Sie
weiter aktiv sind.
Ich konnte mit nuclos.py einen Auftragsimport aus einer Exceldatei nach
Nuclos umsetzen und hoffe, dass wir dies bald produktiv einsetzen.
VG Dirk Jende-Holzmann

Am Sa., 2. Jan. 2021 um 12:06 Uhr schrieb Daniel Saier <
***@***.***>:
