### ISSUE TITLE
Bug: change_to_state not working

### ISSUE THREAD

**Issue by andreheuer** [saierd/python-nuclos#5]
First of all: thank you for the great work and this script. That really helps a lot.

Unfortunately, I do have the following issue with Nuclos 4.2022.12 (docker hosted): I do have a BO with different states and I want to change the state of the BO by number. When calling change_to_state (with a valid state number) the following exception is raised:
```
Traceback (most recent call last):
  File "/app/nuclos.py", line 361, in request
    result = urllib.request.urlopen(request)
  File "/usr/local/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 405: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/lib/python3.9/site-packages/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/app/actions.py", line 41, in action
    abrechnung.change_to_state_by_name(new_state)
  File "/app/nuclos.py", line 796, in change_to_state_by_name
    self._change_to_state(self._get_state_id_by_name(name))
  File "/app/nuclos.py", line 776, in _change_to_state
    self._nuclos.request(url, json_answer=False)
  File "/app/nuclos.py", line 388, in request
    raise NuclosHTTPException(e)
nuclos.NuclosHTTPException: HTTP Exception: 405 - 
```
I already had a look into the code and it seems that in https://github.com/saierd/python-nuclos/blob/3390d453952744c9bc1ec2d4c1ddc99adf2335e3/nuclos.py#L761 the list of reachable states are iterated and compared to the "number" attribute. However, there is no number attribute (anymore?).

Please find an excerpt below:
```
    "nextStates":[
       {
          "nuclosStateId":"de_andreheuer_pkv_basis_AbrechnungSM_State_20",
          "name":"XXX1",
          "nonstop":false,
          "transitionname":"XXXXX1"
       },
       {
          "nuclosStateId":"de_andreheuer_pkv_basis_AbrechnungSM_State_21",
          "name":"XXX2",
          "nonstop":false,
          "transitionname":"XXXXX2"
       }
    ],
```

**Comment by saierd** [comment]
Thank you for reporting this.

It looks like the state number was removed from the API and replaced with a separate API call in [this Nuclos commit](https://bitbucket.org/nuclos/nuclos/commits/a5dc5c714d948e09fa3f30ca0f195a9c5a0475ca).

To avoid this separate API call, I just hacked together an extraction of the state number from the state id in the [`state_number` branch](https://github.com/saierd/python-nuclos/tree/state_number). Unfortunately, I don't have easy access to a running Nuclos right now, so the change was done blindly. Could you please test this?
